# Generated by Django 3.0.2 on 2020-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albreleasedate',
            field=models.DateField(verbose_name='Relase Date'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(verbose_name='Borrow Date'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='exp_return_date',
            field=models.DateField(verbose_name='Expect Return Date'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='first_monit_date',
            field=models.DateField(null=True, verbose_name='1st Monit Date'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(null=True, verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='second_monit_date',
            field=models.DateField(null=True, verbose_name='2nd Monit Date'),
        ),
    ]
